test:
    pytest test
language: python
cache: pip
python: "3.5"
install:
    - pip install -U pytest
    - pip install -U requests
script: PYTHONPATH=. pytest test
after_sucess:
  - CODECLIMATE_REPO_TOKEN=40748b63a30c248369f19e5255e8bec726d7a7a25708a597bdf1181b71fc63e3 codeclimate-test-reporter