test:
    pytest test
sudo: false
language: python
cache: pip
python: "3.5"
install:
    - pip install -U pytest
    - pip install -U requests
    - pip install -U urllib
script: PYTHONPATH=. pytest test
